# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "SHOP"
  url = "/shop"
  weight = 10

[[main]]
  name = "OUR STORY"
  url = "/about"
  weight = 20

[[main]]
  name = "OUR SCIENCE"
  url = "/science"
  weight = 30

[[main]]
  name = "A SUSTAINABLE CHOICE"
  url = "/sustainability"
  weight = 40  

[[main]]
  name = "SAVING OUR RAINFORESTS"
  url = "/the-palm-oil-problem"
  weight = 50  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
